# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ea3935e4477b576c5782cbfcf5602fdc5d2877e573fda4628739ff7afd60288a01f77cd6c10ada63067df052faba7fe28f0f48193fa189e1f15f2a9d1bc85d5

test:
  secret_key_base: 0f5fbcf89988611cf015f033bfaf2f150df835ebfda35cfa661b2cf5f1105685b89b77b9d52554a603d309363c9c1a0bd1db8d99d8d7e8a56d405a1c2367888d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
